name: 'Angular Github Super Actions'
description: 'Actions to super-charge your angular app for GitHub. Runs tests, performs lint actions and then deploys your specific folder to Github'
author: 'Muhammad Ahsan Ayaz (https://github.com/ahsanayaz)'

# branding:
#   icon: 'layers'
#   color: 'red',
#   label: 'Angular Github Super Actions'

inputs:
  github_access_token:
    description: "Github access token token used to deploy on gh_pages. You can find it on Github."
    required: true
  build_configuration:
    description: "Build configuration for the angular app"
    default: "production"
    required: true
  base_href:
    description: "base href for the app"
    default: "/"
    required: true
  deploy_branch:
    description: "branch on which the angular build will be deployed"
    default: "gh-pages"
    required: true
  deploy_folder:
    description: "The folder from which the code will be deployed to gh_pages."
    required: true
  run_lint:
    description: "If the action should run 'ng lint'"
    default: false

runs:
  using: 'node12'
  main: 'action.js'
