# GitHub Actions docs
# https://help.github.com/en/articles/about-github-actions
# https://help.github.com/en/articles/workflow-syntax-for-github-actions
name: CI

on:
  pull_request:
    branches:
      - master

jobs:
  build:

    # Machine environment:
    # https://help.github.com/en/articles/software-in-virtual-environments-for-github-actions#ubuntu-1804-lts
    # We specify the Node.js version manually below, and use versioned Chrome from Puppeteer.
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Angular magic
      uses: ./.github/actions/angular-magic
      with:
        github_access_token: ${{ secrets.ACCESS_TOKEN }}
        build_configuration: development # The branch the action should deploy from.
        base_href: /ngrx-workshop/
        deploy_branch: gh-pages # The branch the action should deploy to.
        deploy_folder: dist # The folder the action should deploy.
